name: pytest
on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    types: [opened]
  schedule:
    - cron: "*/5 * * * *"

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: print github action contexts
        run: echo ${{ github.repositoryUrl }}
      - name: checkout code
        uses: actions/checkout@v4
      - name: install pytest
        run: pip install pytest
      - name: run pytest
        run: pytest
