name: workflow_env
on: workflow_dispatch

env:
  DAY_OF_WEEK: Monday

jobs:
  test-scope-env:
    runs-on: ubuntu-latest
    steps:
      - name: print env
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"

  greeting-job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        env:
          First_Name: Mona
