name: workflow_secrets
on:
  workflow_dispatch:

env:
  DB_U: test
  DB_P: ${{ secret.DB_PASSWORD }}

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: action/checkout@v4
      - name: check env u
        run: echo "u=${{ env.DB_U }}"
      - name: check env p
        run: echo "u=${{ env.DB_P }}"
